set_languages("c++23")
add_rules("mode.debug")
set_toolchains("msvc")

add_repositories("MrowrLib https://github.com/MrowrLib/package-repo.git")
add_requires("StringFormatting")
add_requires("Logging")
add_requires("spdlog")

target("Memory")
    set_kind("library")
    add_headerfiles("include/(**.h)")
    add_includedirs("include", {public = true})
    add_packages("StringFormatting")
    add_packages("Logging")

target("Example")
    set_kind("binary")
    add_files("Example.cpp")
    add_deps("Memory")
    add_imports("Memory")
    add_packages("StringFormatting")
    add_packages("Logging")
    add_packages("spdlog")
